Document: iotivity-example
Title: Debian iotivity-example Manual
Author: <insert document author here>
Abstract: This manual describes what iotivity-example is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/iotivity-example/iotivity-example.sgml.gz

Format: postscript
Files: /usr/share/doc/iotivity-example/iotivity-example.ps.gz

Format: text
Files: /usr/share/doc/iotivity-example/iotivity-example.text.gz

Format: HTML
Index: /usr/share/doc/iotivity-example/html/index.html
Files: /usr/share/doc/iotivity-example/html/*.html
